# https://taskfile.dev

version: '3'
vars:
  GREETING: Hello, World!
tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  stage:
    vars:
      RECIPIENT: '{{.msg}}'
    cmds:
      - echo "commiting '{{.msg}}'"
      - git add .
      - git commit -S -m "{{.msg}}"
      - git cliff -o CHANGELOG.md
      - git add CHANGELOG.md
      - git commit -S -m "Updated Changelog.md"
